# Generated by Django 3.2.13 on 2023-04-14 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_hate_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='origin_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movies.comment'),
        ),
    ]
